
package org.example;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countPersons", targetNamespace = "http://example.org/", className = "org.example.CountPersons")
    @ResponseWrapper(localName = "countPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.CountPersonsResponse")
    int countPersons();

    /**
     * 
     * @return
     *     returns java.util.List<org.example.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPersons", targetNamespace = "http://example.org/", className = "org.example.GetAllPersons")
    @ResponseWrapper(localName = "getAllPersonsResponse", targetNamespace = "http://example.org/", className = "org.example.GetAllPersonsResponse")
    List<Person> getAllPersons();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.example.Person
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://example.org/", className = "org.example.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://example.org/", className = "org.example.GetPersonResponse")
    Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://example.org/", className = "org.example.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://example.org/", className = "org.example.DeletePersonResponse")
    boolean deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws PersonNotFoundEx_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns org.example.Person
     * @throws PersonExistsEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://example.org/", className = "org.example.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://example.org/", className = "org.example.AddPersonResponse")
    Person addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws PersonExistsEx_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns org.example.Person
     * @throws PersonNotFoundEx_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://example.org/", className = "org.example.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://example.org/", className = "org.example.UpdatePersonResponse")
    Person updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws PersonNotFoundEx_Exception
    ;

}
