
package org.example;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PersonNotFoundEx", targetNamespace = "http://example.org/")
public class PersonNotFoundEx_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private final PersonNotFoundEx faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonNotFoundEx_Exception(String message, PersonNotFoundEx faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public PersonNotFoundEx_Exception(String message, PersonNotFoundEx faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.example.PersonNotFoundEx
     */
    public PersonNotFoundEx getFaultInfo() {
        return faultInfo;
    }

}
